### ISSUE TITLE
RP2040 build instructions - pico_sdk 2.0 compatibility

### ISSUE THREAD

**Issue by SanguineBrah** [harbaum/FPGA-Companion#7]
It looks like the latest pico_sdk (2.0) omits stdlib.h so the current source won't make without installing the previous release.

**Comment by harbaum** [comment]
I would be very surprised if stdlib was not supported in the pico sdk, anymore. Many projects would run into this.

**Comment by SanguineBrah** [comment]
It looks like it has moved [here](https://github.com/raspberrypi/pico-sdk/blob/master/src/common/pico_stdlib_headers/include/pico/stdlib.h) in the src folder but set_sys_clock_khz has been removed from the file, which prevents the build.

**Comment by darius600** [comment]
I just successfully built FPGA-Companion 1.0.0 with pico-sdk SDK 2.0.0. 
Initially, I encountered some issues. 
They were resolved after I deleted FPGA-Companion and started from scratch by cloning the repository again.

Note the line: _You should delete/recreate all build directories when upgrading from previous versions of the Raspberry Pi Pico SDK 2.0.0_ in the [release notes](https://github.com/raspberrypi/pico-sdk/releases/tag/2.0.0).

Maybe this is the reason here.

**Comment by SanguineBrah** [comment]
> I just successfully built FPGA-Companion 1.0.0 with pico-sdk SDK 2.0.0. Initially, I encountered some issues. They were resolved after I deleted FPGA-Companion and started from scratch by cloning the repository again.
> 
> Note the line: _You should delete/recreate all build directories when upgrading from previous versions of the Raspberry Pi Pico SDK 2.0.0_ in the [release notes](https://github.com/raspberrypi/pico-sdk/releases/tag/2.0.0).
> 
> Maybe this is the reason here.

I just did the same. Wiped my directories and started completely from scratch and it worked this time using the 2.0 SDK.
